### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/bukkitgui2#1]
- [x] Remove Plugins List
- [x] Remove Updater (settings > updater)
- [ ] Fix issue where servers don't appear to be isolated completed.
- [ ] Fix issue where GUI becomes disconnected from server
- [ ] Fix issue where Player List doesn't seem to populate with Sponge Servers
